project_id = "linvrngdhjoblbtrzkmc"

[functions.evaluate-description]
verify_jwt = false

[functions.evaluate-instructions]
verify_jwt = false

[functions.evaluate-triggers]
verify_jwt = false

[functions.evaluate-messy-inputs]
verify_jwt = false

[functions.evaluate-final]
verify_jwt = false